-- HRMS Platform complete consolidated schema for Supabase PostgreSQL
create extension if not exists pgcrypto;
create extension if not exists citext;

create type public.member_role as enum ('owner','admin','hr','manager','employee');
create type public.employee_status as enum ('candidate','selected','offer_sent','offer_accepted','pre_onboarding','onboarding','probation','active','confirmed','notice_period','resigned','offboarded','inactive');
create type public.leave_request_status as enum ('pending','approved','rejected','cancelled');
create type public.approval_status as enum ('pending','approved','rejected');

create table if not exists organizations (id uuid primary key default gen_random_uuid(), name text not null, legal_name text, slug text unique, timezone text default 'Asia/Kolkata', currency text default 'INR', settings jsonb default '{}'::jsonb, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists profiles (id uuid primary key references auth.users(id) on delete cascade, full_name text, email citext, phone text, avatar_url text, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists organization_members (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, role member_role not null default 'employee', status text not null default 'active', joined_at timestamptz default now(), unique(organization_id,user_id));
create table if not exists departments (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id) on delete cascade, name text not null, code text, manager_id uuid, created_at timestamptz default now(), updated_at timestamptz default now(), unique(organization_id,name));
create table if not exists designations (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id) on delete cascade, name text not null, level text, description text, created_at timestamptz default now(), updated_at timestamptz default now(), unique(organization_id,name));
create table if not exists employees (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id) on delete cascade, user_id uuid references auth.users(id) on delete set null, employee_code text, first_name text not null, last_name text, preferred_name text, work_email citext, personal_email citext, phone text, date_of_birth date, gender text, address jsonb default '{}'::jsonb, emergency_contact jsonb default '{}'::jsonb, date_of_joining date, confirmation_date date, employment_type text default 'full_time', department_id uuid references departments(id) on delete set null, designation_id uuid references designations(id) on delete set null, manager_id uuid references employees(id) on delete set null, location text, status employee_status default 'pre_onboarding', photo_url text, bank_details jsonb default '{}'::jsonb, tax_details jsonb default '{}'::jsonb, created_at timestamptz default now(), updated_at timestamptz default now(), unique(organization_id,employee_code));
alter table departments drop constraint if exists departments_manager_id_fkey; alter table departments add constraint departments_manager_id_fkey foreign key(manager_id) references employees(id) on delete set null;
create table if not exists employee_status_history (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id) on delete cascade, employee_id uuid not null references employees(id) on delete cascade, from_status employee_status, to_status employee_status not null, effective_date date default current_date, changed_by uuid references auth.users(id), reason text, created_at timestamptz default now());
create table if not exists employee_changes (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id) on delete cascade, employee_id uuid not null references employees(id) on delete cascade, change_type text not null, before_data jsonb, after_data jsonb, effective_date date default current_date, changed_by uuid references auth.users(id), created_at timestamptz default now());

create table if not exists jobs (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id) on delete cascade, title text not null, department_id uuid references departments(id) on delete set null, designation_id uuid references designations(id) on delete set null, description text, employment_type text, openings int default 1, status text default 'draft', recruiter_id uuid references auth.users(id), opened_at date, closed_at date, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists candidates (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id) on delete cascade, job_id uuid references jobs(id) on delete set null, first_name text not null, last_name text, email citext, phone text, resume_url text, source text, stage text default 'applied', score numeric, notes text, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists interviews (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id) on delete cascade, candidate_id uuid references candidates(id) on delete cascade, scheduled_at timestamptz, interviewer_id uuid references auth.users(id), mode text, score numeric, feedback text, status text default 'scheduled', created_at timestamptz default now());
create table if not exists offers (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id) on delete cascade, candidate_id uuid references candidates(id) on delete cascade, employee_id uuid references employees(id) on delete set null, offer_number text, offered_salary numeric, joining_date date, expires_at date, status text default 'draft', document_url text, sent_at timestamptz, accepted_at timestamptz, created_at timestamptz default now());

create table if not exists onboarding_tasks (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id) on delete cascade, employee_id uuid references employees(id) on delete cascade, title text not null, description text, owner_role text, due_date date, status text default 'pending', completed_at timestamptz, completed_by uuid references auth.users(id), created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists probation_records (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id) on delete cascade, employee_id uuid references employees(id) on delete cascade, start_date date not null, end_date date not null, review_date date, extension_end_date date, status text default 'active', decision text, review_notes text, reviewed_by uuid references auth.users(id), created_at timestamptz default now(), updated_at timestamptz default now());

create table if not exists attendance_locations (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id) on delete cascade, name text not null, address text, latitude double precision not null, longitude double precision not null, radius_meters int default 150, active boolean default true, created_at timestamptz default now());
create table if not exists attendance_records (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id) on delete cascade, employee_id uuid references employees(id) on delete cascade, location_id uuid references attendance_locations(id) on delete set null, attendance_date date generated always as ((clock_in_at at time zone 'Asia/Kolkata')::date) stored, clock_in_at timestamptz, clock_out_at timestamptz, clock_in_latitude double precision, clock_in_longitude double precision, clock_out_latitude double precision, clock_out_longitude double precision, clock_in_distance_meters double precision, status text default 'present', source text default 'web', notes text, created_at timestamptz default now(), unique(employee_id,attendance_date));
create table if not exists attendance_corrections (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id) on delete cascade, attendance_id uuid references attendance_records(id) on delete cascade, employee_id uuid references employees(id) on delete cascade, requested_clock_in timestamptz, requested_clock_out timestamptz, reason text not null, status approval_status default 'pending', approved_by uuid references auth.users(id), approved_at timestamptz, created_at timestamptz default now());

create table if not exists leave_types (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id) on delete cascade, name text not null, code text, annual_quota numeric default 0, carry_forward boolean default false, requires_approval boolean default true, active boolean default true, created_at timestamptz default now());
create table if not exists leave_balances (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id) on delete cascade, employee_id uuid references employees(id) on delete cascade, leave_type_id uuid references leave_types(id) on delete cascade, year int not null, allocated numeric default 0, used numeric default 0, carried numeric default 0, unique(employee_id,leave_type_id,year));
create table if not exists leave_requests (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id) on delete cascade, employee_id uuid references employees(id) on delete cascade, leave_type_id uuid references leave_types(id), start_date date not null, end_date date not null, days numeric not null, reason text, status leave_request_status default 'pending', approver_id uuid references auth.users(id), approved_at timestamptz, created_at timestamptz default now(), updated_at timestamptz default now());

create table if not exists projects (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id) on delete cascade, name text not null, code text, client_name text, description text, start_date date, end_date date, status text default 'active', manager_id uuid references employees(id) on delete set null, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists project_allocations (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id) on delete cascade, project_id uuid references projects(id) on delete cascade, employee_id uuid references employees(id) on delete cascade, role text, allocation_percent numeric default 100, start_date date not null, end_date date, status text default 'active', created_at timestamptz default now());

create table if not exists assets (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id) on delete cascade, asset_tag text not null, category text, name text not null, serial_number text, purchase_date date, purchase_cost numeric, status text default 'available', condition text, details jsonb default '{}'::jsonb, created_at timestamptz default now(), updated_at timestamptz default now(), unique(organization_id,asset_tag));
create table if not exists asset_assignments (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id) on delete cascade, asset_id uuid references assets(id) on delete cascade, employee_id uuid references employees(id) on delete cascade, assigned_at timestamptz default now(), returned_at timestamptz, assigned_by uuid references auth.users(id), returned_condition text, notes text, created_at timestamptz default now());
create table if not exists system_access (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id) on delete cascade, employee_id uuid references employees(id) on delete cascade, system_name text not null, username text, access_level text, provisioned_at timestamptz, revoked_at timestamptz, status text default 'active', notes text, created_at timestamptz default now());

create table if not exists expenses (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id) on delete cascade, employee_id uuid references employees(id) on delete cascade, expense_date date not null, category text, amount numeric not null, currency text default 'INR', description text, receipt_url text, status approval_status default 'pending', approver_id uuid references auth.users(id), approved_at timestamptz, paid_at timestamptz, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists payroll_periods (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id) on delete cascade, name text not null, period_start date not null, period_end date not null, pay_date date, status text default 'draft', created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists payroll_records (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id) on delete cascade, payroll_period_id uuid references payroll_periods(id) on delete cascade, employee_id uuid references employees(id) on delete cascade, gross_salary numeric default 0, allowances numeric default 0, deductions numeric default 0, tax numeric default 0, net_salary numeric generated always as (gross_salary+allowances-deductions-tax) stored, currency text default 'INR', payslip_url text, status text default 'draft', paid_at timestamptz, created_at timestamptz default now());

create table if not exists performance_cycles (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id) on delete cascade, name text not null, start_date date, end_date date, status text default 'draft', created_at timestamptz default now());
create table if not exists performance_goals (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id) on delete cascade, cycle_id uuid references performance_cycles(id) on delete cascade, employee_id uuid references employees(id) on delete cascade, title text not null, description text, weight numeric default 100, target text, progress numeric default 0, status text default 'active', created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists performance_reviews (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id) on delete cascade, cycle_id uuid references performance_cycles(id) on delete cascade, employee_id uuid references employees(id) on delete cascade, reviewer_id uuid references employees(id), rating numeric, strengths text, improvement_areas text, comments text, status text default 'draft', submitted_at timestamptz, created_at timestamptz default now());

create table if not exists documents (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id) on delete cascade, employee_id uuid references employees(id) on delete cascade, document_type text, title text not null, storage_path text, expires_on date, verified boolean default false, verified_by uuid references auth.users(id), created_at timestamptz default now());
create table if not exists resignations (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id) on delete cascade, employee_id uuid references employees(id) on delete cascade, submitted_on date not null, last_working_day date, reason text, status text default 'submitted', approved_by uuid references auth.users(id), approved_at timestamptz, created_at timestamptz default now());
create table if not exists offboarding_tasks (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id) on delete cascade, employee_id uuid references employees(id) on delete cascade, title text not null, owner_role text, due_date date, status text default 'pending', completed_at timestamptz, completed_by uuid references auth.users(id), created_at timestamptz default now());
create table if not exists dashboard_preferences (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, dashboard_type text default 'hr', layout jsonb default '[]'::jsonb, updated_at timestamptz default now(), unique(organization_id,user_id,dashboard_type));
create table if not exists notifications (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id) on delete cascade, user_id uuid references auth.users(id) on delete cascade, type text, title text not null, message text, link text, read_at timestamptz, created_at timestamptz default now());
create table if not exists audit_logs (id uuid primary key default gen_random_uuid(), organization_id uuid not null references organizations(id) on delete cascade, actor_id uuid references auth.users(id), action text not null, entity_type text, entity_id uuid, before_data jsonb, after_data jsonb, ip_address inet, user_agent text, created_at timestamptz default now());

create index if not exists employees_org_status_idx on employees(organization_id,status);
create index if not exists employees_org_manager_idx on employees(organization_id,manager_id);
create index if not exists status_history_employee_idx on employee_status_history(employee_id,created_at desc);
create index if not exists attendance_employee_date_idx on attendance_records(employee_id,attendance_date desc);
create index if not exists leave_employee_idx on leave_requests(employee_id,start_date desc);
create index if not exists projects_employee_idx on project_allocations(employee_id,start_date desc);
create index if not exists assets_employee_idx on asset_assignments(employee_id,assigned_at desc);
create index if not exists payroll_employee_idx on payroll_records(employee_id,created_at desc);
create index if not exists audit_org_idx on audit_logs(organization_id,created_at desc);

create or replace function public.is_org_member(org uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from organization_members m where m.organization_id=org and m.user_id=auth.uid() and m.status='active'); $$;
create or replace function public.is_org_admin(org uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from organization_members m where m.organization_id=org and m.user_id=auth.uid() and m.status='active' and m.role in ('owner','admin','hr')); $$;

alter table organizations enable row level security; alter table profiles enable row level security; alter table organization_members enable row level security;
alter table employees enable row level security; alter table employee_status_history enable row level security; alter table employee_changes enable row level security;

-- Granular RLS Policies
do $$ 
declare 
    t text;
    admin_only text[] := array['departments','designations','jobs','offers','probation_records','attendance_locations','leave_types','leave_balances','projects','project_allocations','assets','asset_assignments','system_access','payroll_periods','payroll_records','performance_cycles','documents','dashboard_preferences'];
    employee_insert text[] := array['candidates','interviews','onboarding_tasks','attendance_records','attendance_corrections','leave_requests','expenses','performance_goals','performance_reviews','resignations','offboarding_tasks','notifications','audit_logs'];
begin 
    for t in select unnest(admin_only || employee_insert) loop 
        execute format('alter table %I enable row level security',t); 
        execute format('drop policy if exists org_member_select on %I',t); 
        execute format('create policy org_member_select on %I for select using (public.is_org_member(organization_id))',t); 
        
        execute format('drop policy if exists org_admin_update on %I',t); 
        execute format('create policy org_admin_update on %I for update using (public.is_org_admin(organization_id)) with check (public.is_org_member(organization_id))',t); 
        execute format('drop policy if exists org_admin_delete on %I',t); 
        execute format('create policy org_admin_delete on %I for delete using (public.is_org_admin(organization_id))',t); 
    end loop; 

    -- Insert policies based on sensitivity
    for t in select unnest(admin_only) loop
        execute format('drop policy if exists org_member_insert on %I',t); 
        execute format('create policy org_member_insert on %I for insert with check (public.is_org_admin(organization_id))',t); 
    end loop;

    for t in select unnest(employee_insert) loop
        execute format('drop policy if exists org_member_insert on %I',t); 
        execute format('create policy org_member_insert on %I for insert with check (public.is_org_member(organization_id))',t); 
    end loop;
end $$;

create policy org_member_select on organizations for select using (exists(select 1 from organization_members m where m.organization_id=id and m.user_id=auth.uid()));
create policy profile_self on profiles for all using (id=auth.uid()) with check (id=auth.uid());
create policy member_self_or_admin on organization_members for select using (user_id=auth.uid() or public.is_org_admin(organization_id));
create policy member_admin_insert on organization_members for insert with check (public.is_org_admin(organization_id) or user_id=auth.uid());
create policy employee_member_select on employees for select using (public.is_org_member(organization_id));
create policy employee_admin_insert on employees for insert with check (public.is_org_admin(organization_id));
create policy employee_admin_update on employees for update using (public.is_org_admin(organization_id)) with check (public.is_org_member(organization_id));
create policy employee_admin_delete on employees for delete using (public.is_org_admin(organization_id));
create policy status_member_select on employee_status_history for select using (public.is_org_member(organization_id));
create policy changes_member_select on employee_changes for select using (public.is_org_member(organization_id));

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,full_name,email) values(new.id,coalesce(new.raw_user_meta_data->>'full_name',new.email),new.email) on conflict(id) do update set email=excluded.email; return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
